language: android
sudo: false
jdk: openjdk8
android:
  components:
    - build-tools-28.0.3
    - extra-android-support
    - extra-android-m2repository
    - android-28
  licenses:
    - '.+'
script:
  - ./gradlew clean assemble check
